### ISSUE TITLE
Content not saving in full width widget container

### ISSUE THREAD

**Issue by pushpendraeci** [aXenDeveloper/ips-full-width-widget-containers#1]
Installed the plugin. Able to place the block on the container but when I refresh the page it disappears. 
FYI I am using IPS 4.6.6

**Comment by aXenDeveloper** [comment]
Disable all third-party mods and try and leave only this one.
After testing, the plug works on IPS 4.6.7.

**Comment by pushpendraeci** [comment]
Tried to disable all plugins/themes/modifications on my live website but it didn't work. Though on a fresh installation on localhost it is working fine. 
Could you pls give me any advice so that I can find the issue and use this on my website?

**Comment by aXenDeveloper** [comment]
I can't reproduce this error. 
Check the error logs.

If you have a modified IPS engine it may not work as well.
